# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db487e3aefd37673e265e4ad3b3c025b00c980e8b613b5a42e92dfeb9f1395a61f7b07470f0403b8383ff36af4a0f7237828e94586698f18a463aa1fa2754482

test:
  secret_key_base: 4c9d68818d0f0ffa25e729a0662ba51c3b2241078666dc4a8758c97be12fadd5c48b7f474cf1349e9fdc19d91a49fc4fe98baea85e36bdc7fb8cbc77d1c6b245

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
